"""Report exporters: PDF/JSON/HTML.

JSON is the simplest; HTML is template-rendered; PDF uses reportlab.
"""
from __future__ import annotations

import io
import json
from typing import Any

from config import AUDIT_DIR


def to_json(report: dict[str, Any]) -> bytes:
    return json.dumps(report, ensure_ascii=False, indent=2).encode("utf-8")


def to_html(report: dict[str, Any]) -> bytes:
    findings = report.get("findings", [])
    riskscore = report.get("riskscore", 0)
    label = report.get("risk_label", "Low")
    rows_html = ""
    for f in findings:
        sev_class = f["severity"].lower()
        rows_html += (
            f"<tr class=\"sev-{sev_class}\">"
            f"<td>{f['category']}</td>"
            f"<td>{f['title']}</td>"
            f"<td>{f['description']}</td>"
            f"<td>{f['weight']}</td>"
            f"<td>{f['severity']}</td>"
            "</tr>"
        )
    if not rows_html:
        rows_html = "<tr><td colspan=\"5\" style=\"text-align:center\">No findings \u2714</td></tr>"

    template = f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <title>Security Audit Report — {report.get('generated_at', '')}</title>
  <style>
    body {{ font-family: 'Segoe UI', Arial, sans-serif; padding: 24px; background:#1e1e2e; color:#e6e6ea; }}
    h1 {{ color: #f5f5ff; }}
    h2 {{ color: #c5c8ff; margin-top: 32px; }}
    .score-box {{ display: inline-block; padding: 16px 24px; border-radius: 12px; font-weight: 700; font-size: 24px;
                  background: {_label_color(label)}; color:#111; }}
    table {{ width: 100%; border-collapse: collapse; margin-top: 12px; }}
    th, td {{ padding: 8px 12px; border: 1px solid #3a3a55; text-align: left; vertical-align: top; }}
    th {{ background:#2a2a40; color:#fff; }}
    tr.sev-info td{{ background:#2a2a40; }}
    tr.sev-low td {{ background:#1f3a1f; }}
    tr.sev-medium td {{ background:#3a3a1f; }}
    tr.sev-high td {{ background:#3a1f1f; }}
    tr.sev-critical td {{ background:#3a1f1f; color:#ff8a8a; font-weight:700; }}
    pre {{ background:#2a2a3a; padding: 12px; border-radius: 8px; overflow:auto; }}
    .footer {{ margin-top:48px; color:#888; font-size:12px; }}
  </style>
</head>
<body>
  <h1>Security Audit Report</h1>
  <p>Generated: <code>{report.get('generated_at', '')}</code> ·
     Duration: {report.get('duration_ms', 0)} ms</p>
  <div class="score-box">Risk Score: {riskscore} ({label})</div>
  <h2>Findings ({len(findings)})</h2>
  <table>
    <thead><tr><th>Category</th><th>Title</th><th>Description</th><th>Weight</th><th>Severity</th></tr></thead>
    <tbody>{rows_html}</tbody>
  </table>
  <h2>Suspicious Countries Watchlist</h2>
  <pre>{", ".join(report.get("data", {}).get("suspicious_countries", []))}</pre>
  <div class="footer">Generated by Windy Smart Dashboard</div>
</body>
</html>"""
    return template.encode("utf-8")


def _label_color(label: str) -> str:
    return {
        "Low": "#7ce67c",
        "Medium": "#ffdf6e",
        "High": "#ff9e5e",
        "Critical": "#ff5b5b",
    }.get(label, "#cccccc")


def to_pdf(report: dict[str, Any]) -> bytes:
    """Render PDF with reportlab. Falls back to a simple table layout."""
    from reportlab.lib import colors
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
    from reportlab.lib.units import cm
    from reportlab.platypus import (
        Paragraph,
        SimpleDocTemplate,
        Spacer,
        Table,
        TableStyle,
    )

    buf = io.BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=A4, leftMargin=2 * cm, rightMargin=2 * cm,
                            topMargin=2 * cm, bottomMargin=2 * cm)
    styles = getSampleStyleSheet()
    body_style = styles["BodyText"]
    body_style.fontSize = 9
    style_title = ParagraphStyle("title", parent=styles["Title"], textColor=colors.HexColor("#3a3a55"))
    style_score = ParagraphStyle("score", parent=styles["Heading1"], textColor=colors.HexColor("#1f3a1f"))
    style_h2 = ParagraphStyle("h2", parent=styles["Heading2"], textColor=colors.HexColor("#444466"))
    style_small = ParagraphStyle("small", parent=body_style, fontSize=8,
                                 textColor=colors.HexColor("#666666"))

    story = []
    story.append(Paragraph("Security Audit Report", style_title))
    story.append(Spacer(1, 12))
    story.append(Paragraph(f"Generated: {report.get('generated_at', '')}", style_small))
    story.append(Paragraph(f"Duration: {report.get('duration_ms', 0)} ms · Suspicious countries:", style_small))
    story.append(Paragraph(", ".join(report.get("data", {}).get("suspicious_countries", [])), style_small))
    story.append(Spacer(1, 12))

    riskscore = report.get("riskscore", 0)
    label = report.get("risk_label", "Low")
    story.append(Paragraph(f"Risk Score: {riskscore} ({label})", style_score))
    story.append(Spacer(1, 24))

    story.append(Paragraph("Findings", style_h2))
    story.append(Spacer(1, 6))

    rows = [["Category", "Title", "Description", "Weight", "Severity"]]
    for f in report.get("findings", []):
        rows.append([
            f["category"], f["title"], Paragraph(f["description"], body_style),
            str(f["weight"]), f["severity"],
        ])
    if len(rows) == 1:
        rows.append(["", "No findings \u2714", "", "", ""])

    table = Table(rows, colWidths=[2.5 * cm, 4 * cm, 6 * cm, 1.5 * cm, 2.5 * cm])
    ts = TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#2a2a40")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#aaaaaa")),
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
    ])
    # Per-row severity coloring.
    for i, f in enumerate(report.get("findings", []), start=1):
        color_map = {
            "info": colors.HexColor("#e6e6f0"),
            "low": colors.HexColor("#d6ebd6"),
            "medium": colors.HexColor("#fff0b8"),
            "high": colors.HexColor("#ffd9b8"),
            "critical": colors.HexColor("#ffb0b0"),
        }
        ts.add("BACKGROUND", (0, i), (-1, i), color_map.get(f["severity"], colors.white))
    table.setStyle(ts)
    story.append(table)
    story.append(Spacer(1, 36))
    story.append(Paragraph("Generated by Windy Smart Dashboard", style_small))

    doc.build(story)
    return buf.getvalue()


def save(report: dict[str, Any], fmt: str) -> str:
    """Save report to disk in AUDIT_DIR and return its file path."""
    fmt = fmt.lower()
    ts = report.get("generated_at", "").replace(":", "-").replace(".", "-")
    fname = f"audit_{ts}.{fmt}"
    path = AUDIT_DIR / fname
    if fmt == "json":
        data = to_json(report)
    elif fmt == "html":
        data = to_html(report)
    elif fmt == "pdf":
        data = to_pdf(report)
    else:
        raise ValueError(f"Unknown format: {fmt}")
    with open(path, "wb") as fh:
        fh.write(data)
    return str(path)
